site_name: PySpark for Climate
theme: material
docs_dir: templates
repo_url: https://github.com/NCAR/PySpark4Climate
site_url: https://ncar.github.io/PySpark4Climate/

pages:

- Home: index.md
- Installation:
  - Yellowstone: installation/yellowstone.md
  - Cheyenne: installation/cheyenne.md
- Usage:
  - Yellowstone: usage/yellowstone.md
  - Cheyenne: usage/cheyenne.md
- PySpark4Climate Package: pyspark4climate.md


markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc(permalink=true)

    

